---
apiVersion: v1
kind: Service
metadata:
  name: tanweercloud
  labels:
    app: tanweercloud
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tanweercloud
  type: LoadBalancer
...
